### ISSUE TITLE
Обработка событий нажатия на пуш

### ISSUE THREAD

**Issue by Vasily-van-Zaam** [mindbox-moscow/flutter-sdk#27]
Здравствуйте!  
Мы интегрируем в наше приложение данное SDK. 
Все выполнили по инструкции указанной здесь https://developers.mindbox.ru/docs/flutter-sdk.  
Столкнулись с проблемой. 
При открытом приложении функция 
``` Dart
Mindbox.instance.onPushClickReceived((link, payload) { 
    // тут делаем обработку 
});
```
отрабатывает нажатия на пуш как нужно,  только при первом запуске и если свернешь приложение и опять нажмешь
на пуш то ```onPushClickReceived``` перестанет работать видать поток переключится на background.   
Если данную функцию поместить в ```FirebaseMessaging.onBackgroundMessage``` то клик на уведомление будет
отработан но в другом потоке и поэтому его нужно будет как-то "ловить".    
Как сделать что бы можно было обработать клик на сообщение когда приложение закрыто или свернуто?
Пуши с firebase нормально отрабатываются в ```FirebaseMessaging.onMessageOpenedApp ``` при открытии приложения, 
но пуши mindbox в ```FirebaseMessaging.onMessageOpenedApp``` не "ловятся"
Что делать уже не знаю. Помогите пожалуйста. Хотя бы пример рабочего кода увидеть как сделана обработка
onBackgroundMessage при закрытом приложении и при просто свернутом и что бы ```onPushClickReceived```
продолжала работать всегда.
Спасибо за ранее за помощь!

**Comment by umbrellait-timur-khismatullin** [comment]
Здравствуйте!
Прошу прощение за столь запоздалый ответ, рад, что проблему удалось успешно решить. Так же от поддержки был получен от Вас фидбек, спасибо!
